name: Codecov

on: [push, pull_request]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Upload requirements
      run: pip install -r requirements.txt
    - name: Install pyteset-cov
      run: |
        pip install pytest
        pip install pytest-cov
    - name: Generate coverage report
      run: |
        pytest --cov=./ --cov-report=xml -s tests
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
